Update jne16.yml

diff --git a/.github/workflows/jne16.yml b/.github/workflows/jne16.yml
--- a/.github/workflows/jne16.yml
+++ b/.github/workflows/jne16.yml
@@ -19,14 +19,17 @@ jobs:
         uses: actions/setup-python@v2
         with:
           python-version: '3.x'
+
       - name: Install dependencies
         run: |
+          python -m pip install --upgrade pip
           if [ -f requirements.txt ]; then
             pip install -r requirements.txt
           else
-            echo "requirements.txt not found"
-            # You can handle this error case as needed
-          fi  
+            echo "Error: requirements.txt not found"
+            exit 1
+          fi
+
   deploy:
     needs: build
     runs-on: ubuntu-latest
@@ -44,7 +47,12 @@ jobs:
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
-          pip install -r requirements.txt
+          if [ -f requirements.txt ]; then
+            pip install -r requirements.txt
+          else
+            echo "Error: requirements.txt not found"
+            exit 1
+          fi
 
       - name: Deployment to production
         run: |
